#!/bin/bash
cat <<EOF > typescript_discord_bot_dbd_tournaments/.env
DOCKERFILE=${DOCKERFILE}
DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
DB_DEPENDENCY_NAME=${DB_DEPENDENCY_NAME}
POSTGRES_PORT=${POSTGRES_PORT}
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=${POSTGRES_DB}
ADMINER_PORT=${ADMINER_PORT}
EOF
echo ".env file generated successfully."
