name: typescript_discord_bot_dbd_tournaments-running_unit_tests
run-name: ${{ github.actor }} - typescript_discord_bot_dbd_tournaments-running_unit_tests
on:
  push:
  workflow_dispatch:
env:
  node_version: 24.7.0
  working_directory: typescript_discord_bot_dbd_tournaments/app
jobs:
  task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: ${{ env.node_version }}
      - run: npm run download
        working-directory: ${{ env.working_directory }}
      - run: npm run test
        working-directory: ${{ env.working_directory }}
